export const sectorPlotSizes: Record<string, string[]> = {
  A: ["1 Kanal", "2 Kanal"],
  B1: ["10 Marla"],
  C: [],
  D: ["1 Kanal"],
  E: ["1 Kanal"],
  E1: ["10 Marla"],
  E2: ["5 Marla"],
  F: ["1 Kanal"],
  G: ["1 Kanal"],
  H: ["1 Kanal"],
  I: ["1 Kanal"],
  K: ["1 Kanal"],
  L: ["1 Kanal"],
  M: ["1 Kanal"],
  N: ["1 Kanal", "2 Kanal"],
  O: ["1 Kanal"],
  P: ["5 Marla"],
  Q: ["1 Kanal"],
  R: ["1 Kanal"],
  S: ["1 Kanal"],
  T: ["5 Marla"],
  U: ["10 Marla", "1 Kanal"],
  V: ["8 Marla", "5 Marla"],
  W1: ["1 Kanal"],
  W2: ["1 Kanal"],
  X: ["1 Kanal"],
  Y: ["1 Kanal"],
};