import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service | Prop Value",
  description:
    "The terms and conditions governing your use of the Prop Value property valuation platform.",
};

export default function TermsOfServicePage() {
  return (
    <main
      className="min-h-screen bg-cover bg-center bg-fixed"
      style={{
        backgroundImage:
          "linear-gradient(160deg, var(--color-primary) 0%, #0B1F3A 60%, #081226 100%)",
      }}
    >
      <div className="mx-auto max-w-5xl px-6 py-20">
        {/* Hero */}
        <div className="mb-12 text-center">
          <span className="inline-block rounded-full bg-orange-500/20 px-4 py-2 text-sm font-medium text-orange-300 backdrop-blur-sm">
            Legal Information
          </span>

          <h1 className="mt-6 text-5xl font-extrabold text-white lg:text-6xl">
            Terms of Service
          </h1>

          <p className="mx-auto mt-5 max-w-2xl text-lg leading-8 text-slate-200">
            These Terms of Service govern your use of Prop Value and explain
            your rights and responsibilities while using our property
            valuation platform.
          </p>
        </div>

        {/* Content */}
        <div className="space-y-8 rounded-3xl border border-white/20 bg-white/95 p-10 shadow-2xl backdrop-blur-md">
          <section>
            <h2 className="mb-3 text-2xl font-bold text-primary">
              Acceptance of Terms
            </h2>

            <p className="text-lg leading-8 text-slate-700">
              By using Prop Value, you agree to these Terms of Service.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-primary">
              Service Description
            </h2>

            <p className="text-lg leading-8 text-slate-700">
              Prop Value provides estimated property values based on
              configurable market rates and property-specific information.
            </p>

            <p className="mt-3 text-lg leading-8 text-slate-700">
              Estimates are for informational purposes only and should not
              be considered official property valuations.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-primary">
              User Responsibilities
            </h2>

            <ul className="list-disc space-y-3 pl-6 text-lg text-slate-700 marker:text-orange-500">
              <li>Provide accurate property information.</li>
              <li>Use the platform lawfully.</li>
              <li>Do not misuse or attempt to damage the service.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-primary">
              Disclaimer
            </h2>

            <p className="text-lg leading-8 text-slate-700">
              Property estimates generated by Prop Value are approximate and
              should not replace professional real estate advice.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-2xl font-bold text-primary">
              Changes
            </h2>

            <p className="text-lg leading-8 text-slate-700">
              We may update these Terms of Service at any time. Continued use
              of the platform constitutes acceptance of the updated terms.
            </p>
          </section>
        </div>

        {/* Button */}
        
          <Link
          href="/"
          className="mt-10 inline-block rounded-lg bg-orange-500 px-6 py-3 font-semibold text-white transition hover:bg-orange-600"
        >
          ← Back to Home
        </Link>
        
      </div>
    </main>
  );
}